CREATE TABLE users (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    createDT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE tasks(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    user_id INTEGER,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(200) NOT NULL,
    status INTEGER DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)